### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by jzombie** [zenOSmosis/speaker.app#186]

**Comment by jzombie** [comment]
# .env file
```env
ADAPTER_IP=192.168.1.100
```

# Docker Comose w/ default adapter IP
```yaml
version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "${ADAPTER_IP:-0.0.0.0}:8080:80"
```
